import tkinter as tk
mainscreen=tk.Tk()
label1=tk.Label(mainscreen,text="your name")
label2=tk.Label(mainscreen,text="your password")
label3=tk.Label(mainscreen,text="your adress")
label4=tk.Label(mainscreen,text="your number")
label1.place(x=10,y=10)
label2.place(x=10,y=50)
label3.place(x=10,y=100)
label4.place(x=10,y=150)
entry1=tk.Entry(mainscreen,bd=1)
entry2=tk.Entry(mainscreen,bd=1,show="*")
entry3=tk.Entry(mainscreen,bd=1)
entry4=tk.Entry(mainscreen,bd=1)
entry1.place(x=120,y=10)
entry2.place(x=120,y=50)
entry3.place(x=120,y=100)
entry4.place(x=120,y=150)
btn=tk.Button(mainscreen,text="login")
btn=tk.Button(mainscreen,text="signup")
btn.place(x=120,y=40)
btn.place(x=120,y=100)
mainscreen.mainloop()